[package]
name = "philips-hue-adapter-rs"
version = "0.1.0"
authors = ["James Hobin <hobinjk@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
nanomsg = "0.6"
